export const FETCH_AWAIT_STATEMENTS='FETCH_AWAIT_STATEMENTS';
export const SELECT_CITY='SELECT_CITY';
export const SELECT_TYPE='SELECT_TYPE';
export const SELECT_AREA='SELECT_AREA';
export const SELECT_ORDER_TYPE='SELECT_ORDER_TYPE';
export const FILTER='FILTER';